name    'surfraz-zabbix'
version '0.0.5'
source 'git://github.com/surfraz/puppet-zabbix.git'
author 'surfraz'
license 'Apache 2.0'
summary 'Puppet module for Zabbix'
description 'puppet module for installing and configuring Zabbix'
project_page 'https://github.com/surfraz/puppet-zabbix'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
dependency 'maestrodev/wget'
dependency 'puppetlabs/mysql'
